### ISSUE TITLE
Honeypot repo is broken

### ISSUE THREAD

**Issue by rcmccartney** [codepath/cybersecurity#34]
This line in the documentation for week 9 is broken:

$ sudo git clone https://github.com/RedolentSun/mhn.git

We should use this repo instead:
https://github.com/threatstream/mhn

**Comment by rlucus** [comment]
Hey, it's been 3 months. Has anything been done to fix this simple problem for the upcoming class?

**Comment by chieger** [comment]
@rlucus Thanks for checking in. Looking into the status an ETA. cc @melophonic

**Comment by melophonic** [comment]
Just updated, thanks for the heads up.
