### ISSUE TITLE
Split out CTF DB into separate server [3/1/2019]

### ISSUE THREAD

**Issue by chieger** [codepath/cybersecurity#36]

**Comment by melophonic** [comment]
Completed

- Setup `security-db` instance (MySQL 5.7)
- Configured network access from `security-capstone-ctf-instance`, `security-weekly-ctf-instance`, and `jenkins-instance` 
- Created `fbctf_capstone` schema and user + updated `settings.ini` on capstone instance
- Created `fbctf_weekly` schema and user + updated `settings.ini` on weekly instance
- Configured grading script on jenkins to use new DBs
