### ISSUE TITLE
Update GitHub based submissions (Assignments 7-9) to use private repos and slightly tweaked deliverables / grading procedures 2/15/2019

### ISSUE THREAD

**Issue by chieger** [codepath/cybersecurity#39]

**Comment by melophonic** [comment]
Touchpoints:

* https://courses.codepath.com/courses/cybersecurity_university/pages/submitting_assignments
* https://courses.codepath.com/courses/cybersecurity_university/unit/7#!assignment
* https://courses.codepath.com/courses/cybersecurity_university/unit/8#!assignment
* https://courses.codepath.com/courses/cybersecurity_university/unit/9#!assignment
