### ISSUE TITLE
Unit 3 Slide deck link points to wrong slide deck.

### ISSUE THREAD

**Issue by rlucus** [codepath/cybersecurity#42]
The link on the Unit 3 tech fellow tab for the slide deck points to Unit 2 instead of Unit 3.

The problem is on this URL: 
https://courses.codepath.com/courses/cybersecurity_university/unit/3#!tech_fellow

The link is found on this line : 
2. (20min) Present the Intro Deck for the Unit

**Comment by chieger** [comment]
@rlucus The link should be updated now. Can you verify?

**Comment by rlucus** [comment]
Verified. Great.

I've also noticed Week 5 and up are using an older format for the tech fellow tab and are pointing to a document that is out of date. I'm unable to find the newer slides for these weeks. Is that in the pipeline to be updated or should another issue be reported for it?

**Comment by chieger** [comment]
@rlucus Yes, that's in the pipeline for updates already. Just pending an update to the deck (in progress)

**Comment by rlucus** [comment]
Sounds great. I'll close this out then and keep an eye out for the updated content.
